homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 1
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customization
frontend:
http:
   api_password: !secret apipass
updater:
discovery:
conversation:
emulated_hue:
history:
logbook:
media_player: !include_dir_merge_list media
#Custom Includes
sensor: !include_dir_merge_list sensors
camera: !include_dir_merge_list camera
zwave: !include zwave/zwave.yaml
light: !include lights/lights.yaml
group: !include_dir_merge_named groups
scene: !include_dir_merge_list scenes
alexa:
  intents: !include_dir_merge_named intents
device_tracker:
  - platform: unifi
    host: !secret unifihost
    username: !secret unifiuser
    password: !secret unifipass